No longer used.  Please see [[https://github.com/iani/emacs-prelude-personal]] for the current version.

My emacs setup, using  [[https://github.com/bbatsov/prelude][emacs-prelude]].

This is a redo started in June 2015.  Previous repo: https://github.com/iani/emacs-prelude

The main code is contained in: https://github.com/iani/emacs-init/blob/master/user/init.org

It is loaded through https://github.com/iani/emacs-init/blob/master/init.el using =org-babel-load-file=

The present set up uses el-get to load several extensions to Org-mode and enable SuperCollider in emacs, from repositories available in my [[https://github.com/iani][github account]].  The el-get recipes for these packages are included here in folder [[recipes]].  They should load automatically on a new install of the present library.

* List of Used Packages
** third party
*** package management

- el-get

*** navigation, movement, command completion, search
- ace-mode
- ido-vertical-mode
- ido-universal
- grizzl
- flx-ido
- helm-swoop
- icicles
- imenu+
- speedbar (actually using: sr-speedbar to include the speedbar window in the main frame)
- multi-occur
- color-moccur
- smex (??? not really used? - helm-M-x has the same functionality and a better interface)

*** window and buffer management
- windmove (built-in)
- buffer-move
- switch-window
*** bookmarks
- bookmark+

*** note taking
- deft :: full-text search and fast access to a set of files in a folder (see also own extension: superdeft, part of own library org-notes.)
*** theme and colors

- powerline :: mode-line enhancement
- moe-theme :: colorful emacs color theme

*** org-mode extensions
- calfw :: calendar framework for org-mode

*** coding support
- paredit :: edit parentheses
- hl-sexp :: highlight symbolic expressions
- hideshow :: (Built-in:) Hide/show nested code blocks
- multiple-cursors :: multiple cursors
- rainbow-delimiters :: rainbow colored delimiters
- litable :: light table: display lisp expression value in buffer.
- linum-relative :: relative line numbers
- er :: expand region, built-in
- evil :: evil mode
- evil-leader :: required for evil-org
- evil-org :: evil keys for org-mode

*** To examine

- FrameMove
- toggle-window-split
** Own libraries

- org-notes :: Note taking framework.  Includes deft extension: superdeft.
- org-pm :: Publish any org-mode file or section to multiple projects
- org-sc :: Evaluate SuperCollider source code blocks from an org-mode buffer.
- sclang :: Enable SuperCollider in Emacs
- sc-snippets :: Select, navigate, evaluate blocks of SuperCollider code separated by comments of the form =//:=.
